# Generated by Django 2.0.5 on 2018-12-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotorMSRGeoTrackingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceLocation',
            fields=[
                ('PlaceId', models.CharField(db_column='Userid', max_length=50, primary_key=True, serialize=False)),
                ('PlaceType', models.CharField(db_column='Level1Name', max_length=50)),
                ('Time', models.DateTimeField()),
                ('Latitude', models.FloatField(db_column='Latitude')),
                ('Longitude', models.FloatField(db_column='Longitude')),
            ],
            options={
                'db_table': 'vwmmPlaceLocation',
                'managed': False,
            },
        ),
    ]
